package msc.ai.ui;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import msc.ai.core.FileOperations;
import msc.ai.model.ResourceFile;
import msc.ai.model.VerificationStatus;

/**
 *
 * @author Keshan De Silva
 */
public class ResourceVerifyWindow extends javax.swing.JFrame
{
    private FileListTableModel tableModel;
    private File selectedFile;
    private JFileChooser fileChooser = new JFileChooser();
    private ContentListTableModel contentListTableModel = new ContentListTableModel();
    private ArrayList<ResourceFile> fileList;
    public ResourceVerifyWindow()
    {
        initComponents();
        fileChooser.setFileFilter(new FileNameExtensionFilter("VeriSign Media Pack", "media"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMediaPack = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        btnUnpack = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelResult = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setTitle("VeriSign Media - Verify Resources");

        jLabel1.setText("Resource Package :");

        txtMediaPack.setEditable(false);
        txtMediaPack.setMinimumSize(new java.awt.Dimension(6, 25));

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/resources/Folder.png"))); // NOI18N
        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenActionPerformed(evt);
            }
        });

        btnVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/resources/Key.png"))); // NOI18N
        btnVerify.setText("(2) Verify");
        btnVerify.setPreferredSize(new java.awt.Dimension(120, 25));
        btnVerify.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVerifyActionPerformed(evt);
            }
        });

        btnUnpack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/resources/package.png"))); // NOI18N
        btnUnpack.setText("(1) Unpack");
        btnUnpack.setPreferredSize(new java.awt.Dimension(120, 25));
        btnUnpack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUnpackActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/resources/Cancel.jpg"))); // NOI18N
        jButton6.setText("Exit");
        jButton6.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });

        tabelResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(tabelResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnpack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMediaPack, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMediaPack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnpack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenActionPerformed
    {//GEN-HEADEREND:event_btnOpenActionPerformed
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
          selectedFile = fileChooser.getSelectedFile();
          txtMediaPack.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Do you want to exis?",
                                            "Exit", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnUnpackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUnpackActionPerformed
    {//GEN-HEADEREND:event_btnUnpackActionPerformed
        contentListTableModel = new ContentListTableModel();
        
        WaitPanel waitPanel = WaitPanel.getInstance();
        JDialog waitDialog = new JDialog(this);
        waitDialog.add(waitPanel);
        waitDialog.pack();
        waitDialog.setLocationRelativeTo(this);
        waitDialog.setVisible(true);
        
        SwingWorker swingWorker = new SwingWorker()
        {
            @Override
            protected Object doInBackground() throws Exception
            {
                fileList = FileOperations.unpackPackage(selectedFile);
                waitDialog.setVisible(false);
                contentListTableModel.addResourceFiles(fileList);
                tabelResult.setModel(contentListTableModel);
                if (tabelResult.getColumnModel().getColumnCount() > 0)
                {
                    tabelResult.getColumnModel().getColumn(0).setCellRenderer(new ImageRenderer());
                }
                
                if (!fileList.isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Unpackage completed successfully", "Unpack", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Unpackage process fail", "Unpack", JOptionPane.WARNING_MESSAGE);
                }
                return fileList;
            } 
        };
        swingWorker.execute();
    }//GEN-LAST:event_btnUnpackActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVerifyActionPerformed
    {//GEN-HEADEREND:event_btnVerifyActionPerformed
        WaitPanel waitPanel = WaitPanel.getInstance();
        JDialog waitDialog = new JDialog(this);
        waitDialog.add(waitPanel);
        waitDialog.pack();
        waitDialog.setLocationRelativeTo(this);
        waitDialog.setVisible(true);
        
        SwingWorker swingWorker = new SwingWorker()
        {
            @Override
            protected Object doInBackground() throws Exception
            {
                ArrayList<VerificationStatus> verificationList = FileOperations.getVerified(fileList);
                contentListTableModel.updateVerificationList(verificationList);
                waitDialog.setVisible(false);

                if (!fileList.isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Verification completed successfully", "Verify", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Verification process fail", "Verify", JOptionPane.WARNING_MESSAGE);
                }
                return fileList;
            } 
        };
        swingWorker.execute();
    }//GEN-LAST:event_btnVerifyActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//    {
//        try
//        {
//            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//        }
//        catch (Exception ex)
//        {
//            Logger.getLogger(ResourceSignWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new ResourceVerifyWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnUnpack;
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelResult;
    private javax.swing.JTextField txtMediaPack;
    // End of variables declaration//GEN-END:variables
}
